### PR TITLE
FIX $table name

### PR DESCRIPTION
**Pull request by terabin**
This change is [Reviewable](https://reviewable.io/reviews/datitisev/flarum-ext-reactions/5)

### CODE REVIEW

**Comment by dav-is** [comment]
There's nothing wrong with the table name.

**Comment by terabin** [comment]
Its strange, I tested here, and the table name just work with this modification.

**Comment by dav-is** [comment]
I never said it wouldn't work. It just isn't broken and the current table name is correct.

**Comment by dav-is** [comment]
OH! My apologies! You're half correct. We'd want to change the migration and just remove the $table variable altogether

**Comment by dav-is** [comment]
I added it into my PR: [here](https://github.com/datitisev/flarum-ext-reactions/pull/7/commits/33cb146523de7f568317da7e12071c7d33db6a00) and [here](https://github.com/datitisev/flarum-ext-reactions/pull/7/commits/a6f2ec65e19e1aa163aa635cbd932df8103808e3). Thanks for saying something!

**Pull request closed without merging**
